[0.8.0] GitHub Actions updates
porter-dev/porter pull request #1013
Opened 2021-08-10 14:58 UTC by anukul

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

After deploying from a launch flow with the Git Repository source, the Porter server adds a GitHub Actions [workflow](https://github.com/anukul/gin-example/commit/3f15765e8c2b7f223338862d89403dac87dd0bd2) and the associated [secrets](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/porter-dev/porter%24%40v0.7.0+file:%5Einternal/integrations/ci/actions/actions%5C.go+create+.*+new+secret&patternType=regexp&case=yes) to the repository. 

This workflow runs `porter update` on every push to the selected branch.

## What is the new behavior?

After deployment, a modal is shown with the contents of the workflow and the secrets.
It also contains a toggle "Push workflow to repository" (default: enabled), in case users want us to skip this step and manage it themselves (e.g. adding to an existing workflow, not using GitHub Actions etc.).

## Technical Spec/Implementation Notes

- Use [YamlEditor](https://sourcegraph.com/github.com/porter-dev/porter@v0.7.0/-/blob/dashboard/src/components/YamlEditor.tsx) component to show the workflow
- Add a new route [`GET /projects/{project_id}/ci/actions`](https://sourcegraph.com/github.com/porter-dev/porter@v0.7.0/-/blob/server/router/router.go?L394), call it to fetch the YAML and the secrets _after_ deployment (since this step needs [release](https://sourcegraph.com/github.com/porter-dev/porter/-/blob/server/api/git_action_handler.go?L73) info)
- Create (and publish) a new GitHub Action - "Update Porter App" that performs the update in a single step, and use it in the workflow.

2021-08-10 15:12 UTC, abelanger5 commented
Looks great! Just one minor thing:

> * Add a new route [`GET /projects/{project_id}/ci/actions`](https://sourcegraph.com/github.com/porter-dev/porter@v0.7.0/-/blob/server/router/router.go?L394), call it to fetch the YAML and the secrets _after_ deployment (since this step needs [release](https://sourcegraph.com/github.com/porter-dev/porter/-/blob/server/api/git_action_handler.go?L73) info)

It should be possible to generate this YAML without requiring release information beyond the release name. In the current user flow, the release name is changeable until the last step. However, I think it's acceptable to modify the user flow so that the release name can only be set on the first step of deployment.

I think that if we show the Github action YAML after the user has configured the rest of the template settings, there is still some initial confusion about what happens when you move beyond the "Link from Github repository" step.

2021-08-10 17:21 UTC, anukul commented
@abelanger5 wrt this
> It should be possible to generate this YAML without requiring release information beyond the release name. 

Can I create the `release.WebhookToken` on the client, or should I instead add a new endpoint for this on the server (to use the existing method [[1]](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/server/api/deploy_handler.go?L121:27) [[2]](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/server/api/release_handler.go?L843:27) of calling [GenerateRandomBytes](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/internal/repository/encrypt.go?L27:6))?

2021-08-10 17:35 UTC, abelanger5 commented
> Can I create the `release.WebhookToken` on the client, or should I instead add a new endpoint for this on the server (to use the existing method [[1]](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/server/api/deploy_handler.go?L121:27) [[2]](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/server/api/release_handler.go?L843:27) of calling [GenerateRandomBytes](https://sourcegraph.com/github.com/porter-dev/porter@5646693316f6044ae5b2632c8b7ca5ba78891932/-/blob/internal/repository/encrypt.go?L27:6))?

I'm a little confused -- the webhook token being generated isn't a requirement to show the YAML, right? You just need to generate a display-only YAML file (without running all of the steps that the `actions` package runs in the `Setup()` function.

2021-08-10 17:40 UTC, anukul commented
I was thinking to also show the secrets. So in case they choose to copy & paste the workflow by themselves, they can also add the secrets that it needs to run.

> ## What is the new behavior?
> 
> After deployment, a modal is shown with the contents of the workflow and the secrets.
>

2021-08-10 17:45 UTC, abelanger5 commented
> I was thinking to also show the secrets. So in case they choose to copy & paste the workflow by themselves, they can also add the secrets that it needs to run.

Ah, I see. In that case, I think there should be separate toggles for writing the secrets and the workflow file (it may be desirable to write the secrets, but not the workflow). In this case, however, there should only be a single secret, the API token that the Porter server will use. Where are you seeing that the webhook token is a secret? (that was the case on previous versions of the server, but should no longer be a requirement) 

But you can create an endpoint for generating an API token to be used. In this case, however, we should add API tokens to the Project Settings screen, where the tokens can be revoked from.

2021-08-11 06:51 UTC, anukul commented
@abelanger5 Noting the conclusion of our discussion here, please confirm if this looks good:

Part 1
---

For the scope of this PR, the new modal will only show the workflow YAML, not the secrets.

If a user disables the "Push workflow to repository" toggle, the workflow will not be pushed, but the secrets will still be created either way.
This allows users to copy & paste the shown YAML into a workflow of their choice, while still having access to the secrets it references.

Part 2
---

Add a new `Version uint` field (default: `1`) to the [`GitActionConfig`](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Aporter-dev%2Fporter.git&branch=0.8.0-github-actions-updates&file=internal%2Fmodels%2Fgitrepo.go&editor=JetBrains&version=v1.2.0&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2&start_row=48&start_col=29&end_row=48&end_col=29) model.

This field will indicate which GitHub Actions workflow is used by a deployment (before [`1`] / after [`2`] v0.7.0 - https://github.com/porter-dev/porter/pull/935) and will be used to decide accordingly whether to create the [env secret](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Aporter-dev%2Fporter.git&branch=0.8.0-github-actions-updates&file=internal%2Fintegrations%2Fci%2Factions%2Factions.go&editor=JetBrains&version=v1.2.0&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2&start_row=309&start_col=24&end_row=309&end_col=39) during release upgrades and rollbacks.

New deployments use the updated workflow, but still create 3 [secrets](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/porter-dev/porter%24%40v0.7.0+file:%5Einternal/integrations/ci/actions/actions%5C.go+create+.*+new+secret&patternType=regexp&case=yes) as per the old workflow. This will be changed so only the API token secret is created now.

2021-08-16 22:42 UTC, anukul commented
Screenshot of GitHub Actions page (after Source Settings):

![image](https://user-images.githubusercontent.com/44864521/129638002-6863e10a-446f-414e-9137-4714e37cdacc.png)


Walkthrough:

https://user-images.githubusercontent.com/44864521/129637861-808ace72-cd8a-4df1-a9a4-11cff036ee77.mov

2021-08-17 15:37 UTC, abelanger5 requested changes
Working great @anukul! Some minor fixes.

2021-08-17 15:37 UTC, abelanger5 commented on cli/cmd/api/domain.go
> +// CreateDNSRecord creates a Github action with basic authentication
Nice catch 🥇

2021-08-17 15:37 UTC, abelanger5 commented on server/api/git_action_handler.go
> +	}
Add return statement here after sending error

2021-08-17 15:48 UTC, abelanger5 requested changes
Some documentation considerations:
- Can you add a link to the update actions repo, if the user chooses **not** to write the workflow? 
- Can you add a section to the docs with some details on the workflow file, and how to add the workflow file to the repo if the user doesn't want to auto-write the workflow? i'm talking about [this doc](https://github.com/porter-dev/porter/blob/master/docs/deploy/applications/deploying-from-git-repo.md).

2021-08-17 17:49 UTC, jnfrati requested changes
Nice work the one that you have here! Left some comments that I would like to discuss before merging 🙌

2021-08-17 17:49 UTC, jnfrati commented on dashboard/src/main/home/launch/launch-flow/SourcePage.tsx
> +  setActionConfig: React.Dispatch<React.SetStateAction<ActionConfigType>>;
Not entirely sure about this one, why tightly couple the prop to something internal to React instead of receiving a function?

2021-08-17 17:49 UTC, jnfrati commented on dashboard/src/main/home/launch/launch-flow/WorkflowPage.tsx
> +export default withRouter(WorkflowPage);
Here is better to use the react router hooks, such as useHistory or useLocation

2021-08-17 17:57 UTC, anukul commented
@abelanger5 added link to porter-update-action:


https://user-images.githubusercontent.com/44864521/129776851-7cc238ab-d70f-473a-8c4a-41ba277068e8.mov

2021-08-17 18:09 UTC, anukul commented on dashboard/src/main/home/launch/launch-flow/SourcePage.tsx
> +  setActionConfig: React.Dispatch<React.SetStateAction<ActionConfigType>>;
Since we use both forms of the `setState` function here, the alternative is:

```js
  setActionConfig: (
    x: ActionConfigType | ((prevState: ActionConfigType) => ActionConfigType)
  ) => void;
```

Should I change it to this?

2021-08-17 19:28 UTC, jnfrati commented on dashboard/src/main/home/launch/launch-flow/SourcePage.tsx
> +  setActionConfig: React.Dispatch<React.SetStateAction<ActionConfigType>>;
Probably it would be better to not use the set function directly, but instead pass a handler function to the SourcePage. If this is not possible, then the typing solution that you described is better as it doesn't depend on some internal React typings 🙌

2021-08-17 21:59 UTC, anukul commented on dashboard/src/main/home/launch/launch-flow/SourcePage.tsx
> +  setActionConfig: React.Dispatch<React.SetStateAction<ActionConfigType>>;
I agree with the refactoring suggestion. I haven't also attended to some other changes, so maybe we can batch them up for later.

I don't think this is an internal type, since it's part of React's ["Top-Level API"](https://reactjs.org/docs/react-api.html).

2021-08-18 13:45 UTC, anukul commented on dashboard/src/main/home/launch/launch-flow/SourcePage.tsx
> +  setActionConfig: React.Dispatch<React.SetStateAction<ActionConfigType>>;
Got it!

2021-08-19 00:31 UTC, abelanger5 submitted a review, later dismissed

2021-08-19 00:48 UTC, abelanger5 requested changes
Hey @anukul this should be ready for merging, but a compilation issue needs to be fixed (believe it came from the most recent commit:

```
/webpack/src/main/home/launch/launch-flow/LaunchFlow.tsx(330,10)
webpack_1      |       TS2739: Type '{ name: string; fullActionConfig: FullActionConfigType; shouldCreateWorkflow: boolean; setShouldCreateWorkflow: Dispatch<SetStateAction<boolean>>; setPage: Dispatch<...>; }' is missing the following properties from type 'RouteComponentProps<{}, StaticContext, unknown>': history, location, match
```

2021-08-19 12:26 UTC, abelanger5 approved these changes

2021-08-19 12:26 UTC, abelanger5 approved these changes

2021-08-19 12:27 UTC, merged