fix: connect term sizing to stream io
porter-dev/porter pull request #1070
Opened 2021-08-18 03:52 UTC by joegilley

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

Tests aren't passing on master right now for me, not sure if its a setup problem or HEAD is broken.
Feel free to commandeer, add tests, change logic, make it your own, whatever you like :)

## What is the current behavior?

Issue Number: #1069

## What is the new behavior?

Interactive shells now use the full terminal width and overdraws correctly continue to the next line.

## Technical Spec/Implementation Notes

Also I added an event watcher to wait for the new pod to be ready instead of polling.

2021-08-19 01:06 UTC, abelanger5 requested changes
Hey @joegilley thanks for this PR -- this is working great! 

Could you also add terminal size queue logic to the `executeRun` function (not just `executeRunEphemeral`)? The difference is essentially the same as `kubectl`'s [`exec`](https://github.com/kubernetes/kubectl/blob/567f2b8c4b5cd2a5b8688f6436ba44ae4b09a80d/pkg/cmd/exec/exec.go#L123) and  [`attach`](https://github.com/kubernetes/kubectl/blob/567f2b8c4b5cd2a5b8688f6436ba44ae4b09a80d/pkg/cmd/attach/attach.go#L161). 

Otherwise, this should be good to include in release `0.8.0`!

2021-08-19 01:06 UTC, abelanger5 commented on cli/cmd/run.go
> +	err = waitForPod(config, newPod)
We may want to print a message above this line to the user indicating that we're waiting for the pod to be ready. In cases where the pod is unscheduleable (see #1032 for reference) the user will be waiting for up to 30 seconds.

2021-08-19 16:12 UTC, joegilley commented
* add helpful prints during wait
* fix multiple race conditions:
  * if the pod is ready before we start listening to events.
  * if the pod exits before we start listening to events.
  * if k8s doesnt know about the new pod yet when we ask for a listener

2021-08-20 13:25 UTC, abelanger5 approved these changes
This is great @joegilley, much cleaner implementation. 

> Tests aren't passing on master right now for me, not sure if its a setup problem or HEAD is broken.

Just to clarify, HEAD is broken and we're only testing specific packages at the moment (sorry about that). There's a large backend refactoring which will hopefully be completed soon, in which case all tests will work again.

2021-08-20 13:25 UTC, merged