[0.8.0] Form ID Assignment Hotfix
porter-dev/porter pull request #1073
Opened 2021-08-18 18:59 UTC by igalakhov

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## What is the current behavior?

Form IDs don't get assignments properly, causing bad validation and final variable computation.

## What is the new behavior?

Form IDs get assigned in a more centralized place.

2021-08-18 21:23 UTC, abelanger5 commented on dashboard/src/components/porter-form/field-components/KeyValueArray.tsx
> +  console.log(vars);
Debug statements?

2021-08-18 21:24 UTC, abelanger5 requested changes
Thanks @igalakhov -- looks like some lingering debug statements?

2021-08-19 14:18 UTC, igalakhov commented on dashboard/src/components/porter-form/field-components/KeyValueArray.tsx
> +  console.log(vars);
Should be removed now

2021-08-19 15:21 UTC, abelanger5 approved these changes

2021-08-19 15:21 UTC, merged