Fix chart sort
porter-dev/porter pull request #1099
Opened 2021-08-23 20:56 UTC by anukul

## Pull request type

Closes #1086, #1090

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

See #1086, #1090

## What is the new behavior?

Sorting works, chart list refreshes for additions / deletions.

## Technical Spec/Implementation Notes

2021-08-23 21:26 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/chart/ChartList.tsx
> +  useEffect(() => {
Probably a useMemo would fit better here

2021-08-23 21:26 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/chart/ChartList.tsx
> +        setCharts((currentCharts) => {
Warning here updating always, we should only update on new versions of the chart, as the websocket will return past versions of some charts too.

2021-08-24 10:39 UTC, anukul commented on dashboard/src/main/home/cluster-dashboard/chart/ChartList.tsx
> +        setCharts((currentCharts) => {
oh, thanks for the heads up. not sure why that's happening 🤔

2021-08-24 15:00 UTC, jnfrati requested changes
It looks really good! I would like @abelanger5 to check the backend change but I think it looks nice.

Although I would like to discuss some stuff on the websocket implementation if its not blocking you too much

2021-08-24 15:17 UTC, abelanger5 approved these changes
Backend looks good @anukul!

2021-08-24 15:53 UTC, jnfrati approved these changes
Looks awesome! Let's merge it :+1:

2021-08-24 15:54 UTC, merged