add pprof endpoints middleware
porter-dev/porter pull request #1481
Opened 2021-11-29 19:38 UTC by ishankhare07

Signed-off-by: Ishan Khare <me@ishankhare.dev>

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [x] If it's a frontend change, Prettier has been run
- [x] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?
Enable pprof profiling endpoints

## Technical Spec/Implementation Notes
Enable pprof profiling endpoints

2021-11-30 00:49 UTC, abelanger5 requested changes

2021-11-30 00:49 UTC, abelanger5 commented on api/server/router/router.go
> +	r.Mount("/debug", chiMiddleware.Profiler())
two things:
1. Can you mount this under `/api/internal/debug` endpoint? 
2. Can you only expose this if an environment variable is set, such as `PPROF_ENABLED`?

2021-12-01 12:33 UTC, portersupport approved these changes

2021-12-01 12:35 UTC, abelanger5 approved these changes

2021-12-01 12:35 UTC, merged