[POR-252] Initial version of Preview Apps CLI
porter-dev/porter pull request #1507
Opened 2021-12-03 13:05 UTC by mnafees

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?

## Technical Spec/Implementation Notes

2021-12-06 12:56 UTC, abelanger5 requested changes

2021-12-06 12:56 UTC, abelanger5 commented on cli/cmd/apply.go
> +	config.SetProject(d.target.Project)
This will set the project/cluster in the config file which seems like a bit of an unpredictable side effect.

2021-12-06 12:56 UTC, abelanger5 commented on cli/cmd/apply.go
> +		source.Version = "v0.13.0"
I believe we can actually set the `source.Version` default to `"latest"` so we don't need to constantly update this -- might require some testing though. 

I think we should require the `source.Name` field at the moment, and just default the `source.Repo` and `source.Version` independently. So this might look more like:

```go
if source.Name == "" {
   return nil, fmt.Errorf("source name required")
}

if source.Repo == "" {
  source.Repo = "https://charts.getporter.dev"
}

if source.Version == "" {
  source.Version = "latest"
}
```

2021-12-06 12:56 UTC, abelanger5 commented on cli/cmd/apply.go
> +	worker.RegisterDriver("", NewPorterDriver) // FIXME: workaround for when driver is not present
Could this be fixed by a PR into the switchboard repo?

2021-12-06 12:56 UTC, abelanger5 commented on cli/cmd/apply.go
> +			registryURL = (*regList)[0].URL
One mistake we made early on was the use of globals everywhere for the CLI package, which was the recommended approach in the cobra examples but in hindsight makes these variables very unpredictable. This should be fine for now, but I just want to flag that the behavior of setting a global deep inside nested functions is an antipattern. There are many other methods in the CLI guilty of this though.

2021-12-06 12:56 UTC, abelanger5 commented on cli/cmd/apply.go
> +	Run: func(cmd *cobra.Command, args []string) {
Make sure to add a `Long` description in the style of the `create/update` commands. `kubectl apply -h` is also a great reference here.

2022-01-11 04:42 UTC, jnfrati approved these changes

2022-01-11 12:53 UTC, abelanger5 submitted a review, later dismissed

2022-01-11 22:43 UTC, merged