[POR-129] Show available new version of the CLI
porter-dev/porter pull request #1614
Opened 2022-01-19 12:37 UTC by mnafees

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Other (please describe): Enhacement

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

N/A

## What is the new behavior?

We now query for and show a message when a new CLI version is available to download.

## Technical Spec/Implementation Notes

2022-01-19 12:38 UTC, mnafees commented on cli/cmd/root.go
> +						color.New(color.FgYellow).Println("A new version of the porter CLI is available to download at https://github.com/porter-dev/porter/releases/latest")
This should eventually show a message asking the user to run 
```sh
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/porter-dev/porter/HEAD/install.sh)"
```
to upgrade the CLI

2022-01-19 12:43 UTC, abelanger5 requested changes
The issue here is that this runs on every CLI command, not all of which are interactive. For example, this will print on `porter update config get-env`, which is meant to print out the environment variables so people can use them in workflows. Could we figure out a way to annotate certain commands and flag combinations so that this isn't printed when we mark a command as "non-interactive"?

2022-01-25 18:28 UTC, abelanger5 requested changes

2022-01-25 18:28 UTC, abelanger5 commented on cli/cmd/root.go
> +
```suggestion
View CLI installation and upgrade docs here: https://docs.porter.run/cli/installation
```

Perhaps we should add a line linking to the installation docs, just in case they didn't install with `brew` on Mac or they haven't run the new install command?

2022-01-28 09:25 UTC, abelanger5 approved these changes

2022-01-28 09:25 UTC, merged