Create separate provisioner service for infrastructure
porter-dev/porter pull request #1638
Opened 2022-01-31 11:32 UTC by abelanger5

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Infrastructure management on Porter currently does not support:
- Upgrading existing infrastructure from the dashboard 
- Viewing the deployment history for infrastructure, and reverting to previous revisions
- Supporting programmatic and custom infrastructure via forms (just like Helm charts)

## What is the new behavior?

To resolve the following issues:
- Support upgrades of existing infrastructure from the dashboard 
- View a history of operations for each infrastructure
- Support rendering `form.yaml` for existing infra

## Technical Spec/Implementation Notes

Some preliminary screenshots (UNSTYLED):

![image](https://user-images.githubusercontent.com/25448214/151786600-fd96019d-849f-4b1d-9d20-07a1063b0159.png)

![image](https://user-images.githubusercontent.com/25448214/151786646-3b2c3916-e5fd-4db8-9975-cf7927baf804.png)

2022-01-31 12:40 UTC, jnfrati requested changes
I left some comments on super minor items, overall it looks awesomely good! :clap:

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/components/InfraResourceList.tsx
> +    return Object.keys(infraState.resources).map((key) => {
Always make sure that you're passing an object, if by any change infraState.resources is filled with anything besides an object this will directly throw an object.
A simple solution would be to use:
```suggestion
    return Object.keys({...(infraState?.resources || {})}).map((key) => {
```

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/components/InfraResourceList.tsx
> +        <RepoName lastItem={false} isSelected={false}>
Add a key to help react render big list items and avoid errors/warnings on console

```suggestion
        <RepoName key={key} lastItem={false} isSelected={false}>
```

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/components/DeployList.tsx
> +        return "The infrastructure configuration was updated";
Super minor but we can avoid an unnecessary return here.

```suggestion
      case "update":
      default:
        return "The infrastructure configuration was updated";
```

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/components/DeployList.tsx
> +  }, [currentProject]);
Remember adding the infra_id to refresh the operations when it changes 

```suggestion
  }, [currentProject, infra_id]);
```

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/ExpandedInfra.tsx
> +  const formData = yaml.load(initYaml);
Not sure if we should encapsulate this one directly on a useMemo as I'm not sure how expensive can be to load the yaml on each rerender.

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/ExpandedInfra.tsx
> +        icon={integrationList[infra.kind].icon}
Just in case, can we add a null casing here (as well as other places using the integrationList)? Wouldn't be the first time where the component cannot render because of the index being undefined/null. 

```suggestion
        name={integrationList[infra.kind]?.label}
        icon={integrationList[infra.kind]?.icon}
```

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/InfrastructureList.tsx
> +            );
You can get a populated version of pushFiltered using the useRouting hook (this is exported from the same file as the common pushFiltered). The only reason the old pushFiltered function is still exported is for backwards compatibility with class components.

2022-01-31 12:40 UTC, jnfrati commented on dashboard/src/main/home/infrastructure/InfrastructureRouter.tsx
> +          return <ExpandedInfra infra_id={parseInt(match.params["infra"])} />;
Instead of using the render function, we can use the [useParams hook](https://v5.reactrouter.com/web/api/Hooks/useparams), this will encapsulate all the logic inside the component and the router will only be responsible for rendering components.

You can find some example of how we're currently using it over [here](https://github.com/porter-dev/porter/blob/master/dashboard/src/main/home/cluster-dashboard/dashboard/node-view/ExpandedNodeView.tsx#L28)

2022-02-02 13:39 UTC, abelanger5 commented
Looks like this was branched from `dev`, closing to use a branch with a much cleaner commit history.

2022-02-02 13:39 UTC, closed without merging