[POR-391] Tag grouping for applications and jobs backup
porter-dev/porter pull request #1982
Opened 2022-05-05 13:29 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [x] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## Motivation

Allow users to tag applications for better organization.

2022-05-06 12:41 UTC, abelanger5 commented on internal/repository/gorm/tag.go
> +	err := repo.db.Model(&models.Tag{}).Where("name IN ?", tags).Where("project_id = ?", release.ProjectID).Find(&populatedTags).Error
```suggestion
	err := repo.db.Where("name IN ?", tags).Where("project_id = ?", release.ProjectID).Find(&populatedTags).Error
```

I could be wrong but I don't think you need the `Model` section since the `Find` statement defines the table for the resource you're looking for.

2022-05-06 12:52 UTC, jnfrati commented on internal/repository/gorm/tag.go
> +	err := repo.db.Model(&models.Tag{}).Where("name IN ?", tags).Where("project_id = ?", release.ProjectID).Find(&populatedTags).Error
Nice! Didn't knew this one :raised_hands:

2022-05-09 12:21 UTC, abelanger5 requested changes

2022-05-09 12:21 UTC, abelanger5 commented on api/server/handlers/project/list_tags.go
> +	tags, err := p.Config().Repo.Tag().ListTagsByProjectId(proj.ID)
```suggestion
	tags, err := p.Repo().Tag().ListTagsByProjectId(proj.ID)
```

2022-05-11 12:04 UTC, jnfrati commented
Replaced by #2011

2022-05-11 12:04 UTC, closed without merging