Implement stack and stack source config name update
porter-dev/porter pull request #2300
Opened 2022-07-28 14:25 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?

## Technical Spec/Implementation Notes

2022-07-28 14:56 UTC, abelanger5 requested changes
Looks pretty good - think there are a few things to clarify to make it more clear what the additional field represents

2022-07-28 14:56 UTC, abelanger5 commented on api/server/handlers/stack/create.go
> +			if len(sourceConfig.SourceConfigID) != 0 {
I think it's more idiomatic to check for the empty string, also reads a bit better (makes the type more clear)

2022-07-28 14:56 UTC, abelanger5 commented on internal/models/stack.go
> +	SourceConfigID string
`SourceConfigID` is a confusing name for this field (we already have an `ID` and a `UID`). Can we call this `StableSourceConfigID` or something along those lines?

2022-07-28 14:57 UTC, jnfrati commented on api/server/handlers/stack/create.go
> +			if len(sourceConfig.SourceConfigID) != 0 {
This would be something like `sourceConfig.SourceConfigID != ""`?

2022-07-28 14:57 UTC, jnfrati commented on internal/models/stack.go
> +	SourceConfigID string
Sounds good!

2022-07-28 14:59 UTC, abelanger5 commented on api/server/handlers/stack/create.go
> +			if len(sourceConfig.SourceConfigID) != 0 {
Yep

2022-07-28 15:24 UTC, mnafees requested changes
Added a few comments about the update stack handler. But all else looks good to me 👍🏽

2022-07-28 15:24 UTC, mnafees commented on api/server/handlers/stack/update_stack_name.go
> +package stack
I think a generalised handler to update the stack with only a few options available like the name of the stack makes sense. This way it would be more future-proof and extensible.

2022-07-28 15:24 UTC, mnafees commented on api/server/router/v1/stack.go
> +	// PATCH /api/v1/projects/{project_id}/clusters/{cluster_id}/namespaces/{namespace}/stacks/{stack_id}/update_name -> stack.NewStackAddApplicationHandler
Going by the above comment, this could then possibly be 
```
PATCH /api/v1/projects/{project_id}/clusters/{cluster_id}/namespaces/{namespace}/stacks/{stack_id}
```

2022-07-28 15:24 UTC, mnafees commented on api/types/stacks.go
> +type UpdateStackNameRequest struct {
This can simply be `UpdateStackRequest`.

2022-07-29 15:27 UTC, abelanger5 approved these changes

2022-07-29 15:28 UTC, merged