Created populate migration script and final touches for StableSourceConfigID
porter-dev/porter pull request #2307
Opened 2022-08-01 21:59 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?

## Technical Spec/Implementation Notes

2022-08-02 12:03 UTC, abelanger5 requested changes

2022-08-02 12:03 UTC, abelanger5 commented on cmd/migrate/main.go
> +	POPULATE_SOURCE_CONFIG_ID string `env:"POPULATE_SOURCE_CONFIG_ID"`
```suggestion
	POPULATE_SOURCE_CONFIG_ID bool `env:"POPULATE_SOURCE_CONFIG_ID"`
```

2022-08-02 13:43 UTC, jnfrati commented on cmd/migrate/main.go
> +	POPULATE_SOURCE_CONFIG_ID string `env:"POPULATE_SOURCE_CONFIG_ID"`
On this case changing it to boolean the condition over line [105](https://github.com/porter-dev/porter/pull/2307/files/232a75def8556203921af1af93797c6a8005aea2#diff-918e5643cec8e9b3393f6301dab40d8e7838fa28b72067549ebbbda244cecd75R105) would still work? 

On dotenv even if you define the type as boolean the env variable is still processed as string. So not sure if this is the same case for golang.

2022-08-02 13:45 UTC, jnfrati commented on api/types/stacks.go
> +type PutStackSourceConfigPaylod struct {
The issue with changing it to Request is that there's already another struct with the name of `PutStackSourceConfigRequest` do you have any other suggestion here?

2022-08-02 13:48 UTC, abelanger5 commented on cmd/migrate/main.go
> +	POPULATE_SOURCE_CONFIG_ID string `env:"POPULATE_SOURCE_CONFIG_ID"`
Yes it'll still work - the `envdecode` library looks for true values like `'true'` or 't` and sets the boolean appropriately

2022-08-02 14:01 UTC, jnfrati commented on api/types/stacks.go
> +type PutStackSourceConfigPaylod struct {
Well, it is still creating a new row over the DB that's why I thought the PUT still made sense.

2022-08-02 14:07 UTC, abelanger5 commented on api/types/stacks.go
> +type PutStackSourceConfigPaylod struct {
From an API consumer's perspective though, it's just an update to the resource's name, because the database primary key isn't sent over the REST API. We shouldn't leak DB logic into the API design - this is also why the database and API types are kept separate.

2022-08-02 19:07 UTC, jnfrati commented on api/types/stacks.go
> +type PutStackSourceConfigPaylod struct {
Sounds good! Just resolved this one 👍

2022-08-03 12:43 UTC, abelanger5 commented on cmd/migrate/main.go
> +	// Simple env variable that will let us know if we should populate the stable_source_config_id column
```suggestion
        // we add a dummy field to avoid empty struct issue with envdecode
	DummyField       string `env:"ASDF,default=asdf"`
	
	// Simple env variable that will let us know if we should populate the stable_source_config_id column
```

2022-08-03 22:58 UTC, closed without merging