fix: status logs freeze on high log inflow
porter-dev/porter pull request #2336
Opened 2022-08-24 17:17 UTC by meehawk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] If it's a frontend change, Prettier has been run

## What is the current behavior?

Currently, for pods that generate a high volume of logs, the logs section in the status page freezes. One possible cause of this could be a large number of re-renders

Steps to reproduce:

1. Launch a Web Template
2. For the docker image, select: `sohamparekh1998/heavy-logger`
3. Status page freezes due to a large number of logs after some time and becomes unusable

## What is the new behavior?

The updates to the logs frame are chunked using a buffer to prevent multiple re-renders in a short span of time

## Technical Spec/Implementation Notes

1. Add a `logsBuffer` to act as a buffer for logs
2. Introduced methods to `flush` buffer and update `logs` for the `currentContainer` in the status tabs
3. Incremented `MAX_LOGS_SIZE` to 5000

2022-08-24 20:36 UTC, jnfrati requested changes
Hey! This looks awesome! Left some comments to see what you think.

2022-08-24 20:36 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +  let logsBuffer: Anser.AnserJsonEntry[][] = [];
The implementation of the logsBuffer looks nice! Although afaik this might get cleared out (resulting on lost logs) by a rerender on the parent. Maybe a useRef could solve this issue?

2022-08-24 20:36 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +        containerLogs.shift();
Not fully sure if this could cause any issue, but maybe here would be nice to remove the first `N=newLogs.length` items of the queue instead of just one to avoid overflowing the containerLogs too much.

2022-08-25 14:30 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +        containerLogs.shift();
@jnfrati awesome catch, just implemented this.

2022-08-25 14:31 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +  let logsBuffer: Anser.AnserJsonEntry[][] = [];
Nice, update as per suggestion in the latest commit

2022-08-26 12:53 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/useLogs.ts
> +        containerLogs.slice(MAX_LOGS);
Hey @meehawk two small items here! Let me know what you think!
 
I think a better approach would be to do:
```suggestion
        const logsToBeRemoved = newLogs.length < LOGS_BUFFER_SIZE ? newLogs.length : LOGS_BUFFER_SIZE;
        containerLogs = containerLogs.slice(logsToBeRemoved);
```

This way we would only be deleting the necessary amount of logs required for the new logs to not pass the  MAX_LOGS size. Although this would leave us on the edge each time, so open to hearing other ideas here! 

Also added on the second line the re-assignation of the containerLogs variable as if we don't do this, the containerLogs will not be updated with the reduced array, [reference docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)

2022-08-27 18:19 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/useLogs.ts
> +        containerLogs.slice(MAX_LOGS);
i think the reason we dont reassign the container array is so that we can still keep the "rendered output" corresponding to the previous logs in the DOM. If we change the reference, we also lose older logs from the UI

2022-08-27 19:00 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/useLogs.ts
> +        containerLogs.slice(MAX_LOGS);
Hey @jnfrati thanks for the suggestion.

1. Agree with the suggestion. Done!
2. Nice catch! Updated the code

2022-08-30 14:27 UTC, jnfrati requested changes
Hey @meehawk!

We ended up testing a little bit more today and found a couple of issues that I described here. Let me know if you need any more clarification around these issues or if you need any help!

2022-08-30 14:27 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/useLogs.ts
> +  useEffect(() => {
While I was testing I noticed that the system logs are not being populated properly. After digging a little bit around the code I noticed that the issue comes from this useEffect, as the logs buffer doesn't differentiate between containerNames, when a user switches tabs to the system logs the flushLogsBuffer ends up overriding the system logs. This might also happen on pods that have more than two containers so it would be nice to consider this case in wich a pod might have N+2 containers.

I think modifying the logsBuffer to be a map of arrays in which each key represents a containerName would be better. What do you think?

2022-08-30 14:27 UTC, jnfrati commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +          <span className="line-number">{log.lineNumber}</span>
This log line number works pretty good! But we noticed that it breaks ansi-based parsing, could you take a look at it? 

You can replicate this using the supertest2014/nyan container image 🙌 

Before log line number:
![Screen Shot 2022-08-30 at 11 25 01](https://user-images.githubusercontent.com/23369263/187463020-b2e86807-7669-453a-97e9-a01bcd74eed1.png)

After log line number:
![image](https://user-images.githubusercontent.com/23369263/187462594-ee268d9f-ab49-4201-933e-4f424eaaff8a.png)

2022-09-01 18:49 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/Logs.tsx
> +          <span className="line-number">{log.lineNumber}</span>
@jnfrati resolved the issues.Thanks for the catch!

2022-09-01 18:49 UTC, meehawk commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/status/useLogs.ts
> +  useEffect(() => {
Done 🚀

2022-09-05 11:45 UTC, jnfrati commented
Looks awesome! 
Thanks for all the work around this issue!

2022-09-05 12:01 UTC, merged