[POR-779] Enable custom namespaces and namespace annotations for preview environments
porter-dev/porter pull request #2544
Opened 2022-11-03 17:50 UTC by mnafees

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?

## Technical Spec/Implementation Notes

2022-11-04 16:53 UTC, abelanger5 requested changes
Looks great @mnafees 💯 

Just a few smaller comments/suggestions to address.

2022-11-04 16:53 UTC, abelanger5 commented on api/server/handlers/cluster/update.go
> +	if request.PreviewEnvsEnabled != nil {
I thought we added a check to make sure the project had preview envs enabled here? Is that cased elsewhere?

2022-11-04 16:53 UTC, abelanger5 commented on api/server/handlers/environment/create.go
> +	if !project.PreviewEnvsEnabled {
I think we should move this to shared auth middleware that gets registered for preview-specific endpoints.

2022-11-04 16:53 UTC, abelanger5 commented on cmd/migrate/main.go
> +	EnableClusterPreviewEnvs bool `env:"ENABLE_CLUSTER_PREVIEW_ENVS"`
I think we should cherry-pick the migration mechanism from Advanced RBAC and require this migration to be run. For all self-hosted instances, it'll be difficult to toggle on this environment variable.

2022-11-09 14:54 UTC, abelanger5 requested changes

2022-11-09 14:54 UTC, abelanger5 commented on cmd/migrate/main.go
> +				err := fn(db, logger)
I think we'll want to add a `lock` field to the `DbMigration` model to prevent concurrent migrations from running. This wasn't as crucial when we were just doing `AutoMigrate`, but is important if we're running one-off migration scripts.

2022-11-09 14:56 UTC, mnafees commented on cmd/migrate/main.go
> +				err := fn(db, logger)
Aha, nice catch! Will fix this.

2022-11-09 18:29 UTC, abelanger5 commented on cmd/migrate/main.go
> +		if err := db.Raw("LOCK TABLE db_migrations IN SHARE ROW EXCLUSIVE MODE").Error; err != nil {
Should this be `tx.Raw` or is that not supported via `gorm`?

2022-11-09 19:15 UTC, abelanger5 approved these changes

2022-11-09 19:15 UTC, merged