Change all template paths to be project-scoped
porter-dev/porter pull request #2551
Opened 2022-11-09 13:24 UTC by abelanger5

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [X] Other (please describe): improve scoping of template endpoints

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Endpoints to retrieve templates are user-scoped, rather than project-scoped. 

## What is the new behavior?

Make all template endpoints project-scoped. We've moved the project-scoped endpoints to `/api/v1` and we'll keep the old user-scoped template endpoints around for a few releases to prevent immediate breaking changes. 

## Technical Spec/Implementation Notes

2022-11-09 19:47 UTC, mnafees requested changes
Just a few comments, but looks great overall 👍🏽

2022-11-09 19:47 UTC, mnafees commented on api/client/template.go
> +			"/v1/projects/%d/templates/%s/%s",
Can we keep this consistent with the `GET /api/v1/projects/{project_id}/clusters/{cluster_id}/namespaces/{namespace}/env_groups/{name}/versions/{version}` v1 API endpoint and scope it with the `/versions/` prefix?

2022-11-09 19:47 UTC, mnafees commented on api/server/handlers/v1/template/get.go
> +	name, _ := requestutils.GetURLParamString(r, types.URLParamTemplateName)
Should we be checking for the existence of this URL param? If it is empty the `LoadChartPublic()` might throw an error, right?

2022-11-09 19:47 UTC, mnafees commented on api/server/handlers/v1/template/get.go
> +	res.Values = chart.Values
We should set the `RepoURL` field as well here for more transparency.

2022-11-09 19:47 UTC, mnafees commented on api/server/handlers/v1/template/get_upgrade_notes.go
> +	name, _ := requestutils.GetURLParamString(r, types.URLParamTemplateName)
Same validation as the above comment.

2022-11-09 19:47 UTC, mnafees commented on api/server/router/v1/project.go
> +					"%s/templates/{%s}/{%s}",
Same as above comment in `api/client/template.go` about the `/versions/` prefix.

2022-11-09 20:41 UTC, mnafees approved these changes

2022-11-18 14:35 UTC, meehawk approved these changes

2022-11-21 13:33 UTC, merged