[POR-791] use correct GAR image URI during launch flow
porter-dev/porter pull request #2557
Opened 2022-11-14 11:37 UTC by mnafees

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [x] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

When using a GAR registry, the new release image should be of the form `<region>-docker.pkg.dev/<GCP project ID>/<repo><image>`. The `porter create` command cases for this but the dashboard launch flow does not.

## What is the new behavior?

The dashboard launch flow cases on the image repo URI and if it belongs to a GAR registry, then it appends the `<image` part as mentioned above.

## Technical Spec/Implementation Notes

2022-11-14 13:31 UTC, meehawk requested changes

2022-11-14 13:31 UTC, meehawk commented on dashboard/src/main/home/launch/launch-flow/LaunchFlow.tsx
> +    if (imageRepoUri.includes("pkg.dev")) {
minor but can we rename this to `imageRepoURI` since I think in camelCasing we spell abbreviations with all caps.

2022-11-15 14:11 UTC, abelanger5 approved these changes

2022-11-15 22:56 UTC, meehawk approved these changes

2022-11-17 13:55 UTC, merged