Gpu slider
porter-dev/porter pull request #3808
Opened 2023-10-12 22:40 UTC by sdess09

## POR-

## What does this PR do?

2023-10-19 18:15 UTC, ferozemohideen requested changes

2023-10-19 18:15 UTC, ferozemohideen commented on dashboard/src/shared/ClusterResourcesContext.tsx
> +  gpuNodes?: boolean;
remove conditional

2023-10-19 18:15 UTC, ferozemohideen commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                value={value?.value.toString() ?? ".5"}
Why is value possibly undefined? You should set a default value for it in the form so that you can just use value.value.toString() here

2023-10-19 18:15 UTC, ferozemohideen commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                disabled={value?.readOnly}
use value.readOnly

2023-10-19 18:42 UTC, sdess09 commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +    const [gpuNodes, setGpuNodes] = useState(true);
Looks like A commit was lost somehow

2023-10-19 19:06 UTC, ferozemohideen requested changes

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                step={.1}
why is the max 1? also didn't stefan say that it needs to be a whole number?

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/JobTabs.tsx
> +            gpuNodes={gpuNodes}
this is unused

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +        instanceType: "",
make the default instance type t3 medium since the other defaults use that

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +    const [gpuNodes, setGpuNodes] = useState(true);
default state should be false

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +                if (item.instanceType?.includes("g4dn"))
no need for optional, instanceType is defined in every item

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +                if (item.instanceType?.includes("g4dn"))
also, is stefan not doing this logic on the backend? if the getClusterNodes call returns a flag like "clusterContainsGPUNodes" then we wouldn't have to update the front-end, backend can determine what a gpu node vs what isnt

2023-10-19 19:06 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +            console.log("hasGd4nInstance", hasGd4nInstance)
remove

2023-10-19 19:10 UTC, sdess09 commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/JobTabs.tsx
> +            gpuNodes={gpuNodes}
still needs to be passed in now that gpuNodes is required

2023-10-19 19:10 UTC, sdess09 commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                step={.1}
Will be addressed in a later PR

2023-10-19 19:14 UTC, sdess09 commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +                if (item.instanceType?.includes("g4dn"))
will be at a later date- will change that logic when thats implemented

2023-10-19 19:14 UTC, sdess09 commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                step={.1}
only in GKE

2023-10-20 20:25 UTC, ferozemohideen requested changes

2023-10-20 20:25 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +            instanceType: "g4dn.xlarge",
remove

2023-10-20 20:25 UTC, ferozemohideen commented on dashboard/src/lib/hooks/useClusterResourceLimits.ts
> +    const [gpuNodes, setGpuNodes] = useState(false);
nit: rename this to `clusterContainsGPUNodes` throughout

2023-10-20 20:25 UTC, ferozemohideen commented on dashboard/src/main/home/app-dashboard/validate-apply/services-settings/tabs/Resources.tsx
> +                  value.readOnly
this is only going to show up if the first condition is true, so you can get rid of the second string

2023-10-20 20:43 UTC, ferozemohideen approved these changes

2023-10-20 20:44 UTC, merged