Stripe integration frontend
porter-dev/porter pull request #4429
Opened 2024-03-21 17:22 UTC by MauAraujo

## POR-2413

## What does this PR do?
This PR adds all frontend changes related to the Stripe integration. The most important changes are:
- Rework the Billing tab shown under project settings
- Add the `BillingModal` that can be reused to add payment methods
- Add the Stripe `PaymentElement` to collect payment details
- Add api routes that correspons to the ones created in 
- Add stripe publishable key to configuration

## Implementation
I decided to use the Stripe  library since it has some pre-made elements that take care of validation. They also handle redirects to specific credit card confirmation pages, and it allows the page to be compliant. It's recommended by Stripe to use those pre-made elements.

## Screenshots

2024-03-21 19:48 UTC, ferozemohideen requested changes
Overall this is a good start - would recommend using `useQuery` and `zod` validation for backend calls and also you should turn `simplified_view_enabled` on to see the new dashboard style

2024-03-21 19:48 UTC, ferozemohideen commented on dashboard/src/main/home/modals/PaymentSetupForm.tsx
> +            <SubmitButton className='submit-button' text={"Add Payment Method"} disabled={!stripe || loading} onClick={handleSubmit}>
we have a Button component in `components/porter`, that will allow you to pass in an error message

2024-03-21 19:48 UTC, ferozemohideen commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +  }, []);
can replace this with a `useQuery`. See how it's used in one of the `/lib/hooks/` files for an example, basically handles data fetching and tracking loading states for you

2024-03-21 19:48 UTC, ferozemohideen commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +    setPaymentMethods(paymentMethods.filter(elem => elem !== paymentMethod))
I would put these methods in a file called `/lib/hooks/useStripe.ts` to separate the logic from component styling

2024-03-21 19:48 UTC, ferozemohideen commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +        </Helper>
we use the `Text` component in `components/porter`, with color='helper' attribute

2024-03-21 19:48 UTC, ferozemohideen commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +  const [paymentMethods, setPaymentMethods] = useState([]);
this should be typed

2024-03-22 15:18 UTC, MauAraujo commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +  }, []);
Ok, I moved all Stripe specific logic to  `/lib/hooks` and rewrote to use   `useQuery`

2024-03-22 15:18 UTC, MauAraujo commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +    setPaymentMethods(paymentMethods.filter(elem => elem !== paymentMethod))
Thanks for the suggestion, moved in latest commit

2024-03-22 15:18 UTC, MauAraujo commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +  const [paymentMethods, setPaymentMethods] = useState([]);
Fixed!

2024-03-22 15:19 UTC, MauAraujo commented on dashboard/src/main/home/project-settings/BillingPage.tsx
> +        </Helper>
Got it, changed to use `Text` instead of the `Helper` component

2024-03-22 20:36 UTC, closed without merging