Add stripe integration backend changes
porter-dev/porter pull request #4430
Opened 2024-03-21 17:26 UTC by MauAraujo

## POR-2413
## What does this PR do?
This PR introduces all backend changes for the Stripe integration. The most notable changes are:

- Introduce new billing routes under `/project/{project_id}/billing`
- Introduce the `StripeManager` which interacts with the Stripe API to setup payment methods
- Add the `BillingID` column to the projects table, which represents the Stripe customer ID
- Add Stripe Secret Key to configuration

Some of the old code is commented so that I could use the existing abstractions, but I plan to clean up all old billing code in a future PR.

This PR goes in hand with the frontend changes in #4429

2024-03-21 20:03 UTC, ferozemohideen requested changes

2024-03-21 20:03 UTC, ferozemohideen commented on internal/billing/stripe..go
> +func (s *StripeBillingManager) CreateCustomer(userEmail string, proj *models.Project) (customerID string, err error) {
this doesn't need to be a pointer

2024-03-21 20:03 UTC, ferozemohideen commented on internal/billing/stripe..go
> +}
do we need to include these no-op methods?

2024-03-21 20:03 UTC, ferozemohideen commented on api/server/shared/config/loader/loader.go
> +	if sc.StripeSecretKey == "" {
this is going to break our local set up if we don't include the key - can we just not create a stripe client if this variable isn't set?

2024-03-21 20:38 UTC, MauAraujo commented on api/server/handlers/billing/create.go
> +	proj, _ := r.Context().Value(types.ProjectScope).(*models.Project)
Got it, I added telemetry to all billing handlers in my latest commit.

2024-03-21 20:39 UTC, MauAraujo commented on api/server/handlers/billing/customer.go
> +func (c *CreateBillingCustomerIfNotExistsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
added in latest commit!

2024-03-21 20:39 UTC, MauAraujo commented on api/server/handlers/billing/customer.go
> +func NewCreateBillingCustomerIfNotExists(
You are right, I was trying to be explicit but the name ended up being too long. Fixed in my latest commit

2024-03-21 20:40 UTC, MauAraujo commented on api/server/handlers/billing/create.go
> +		c.HandleAPIError(w, r, apierrors.NewErrInternal(fmt.Errorf("error creating payment method: %w", err)))
Ok, I added error reporting using telemtry as the other handlers. Let me know if that is the correct way.

2024-03-21 20:43 UTC, MauAraujo commented on api/server/handlers/billing/customer.go
> +	if proj.BillingID != "" {
The billing id is not exposed to the user, as it's internal to Stripe (and the billing implementation). I don't see a scenario where the user would need to update the billing id, as they can manage their billing details through the dashboard, and that is the only part they need to see. I added this field it to the database so we could map each project to a stripe customer, so payment methods are set per project.  Let me know what you think

2024-03-21 20:43 UTC, MauAraujo commented on api/server/handlers/billing/delete.go
> +	paymentMethodID, reqErr := requestutils.GetURLParamString(r, types.URLParamPaymentMethodID)
added in latest commit!

2024-03-21 20:47 UTC, MauAraujo commented on api/server/shared/config/loader/init_ee.go
> +	// TODO: delete once the billing code is cleaned up
Ok, the reason I left it in (and also the no-op methods below) is because there are still many places in the code which reference the old billing code, and it felt out of scope for this PR to delete those old parts of the code. I was hoping to create a follow-up PR once this is done to remove all the old billing implementation. Let me know what you think, otherwise I could delete it in this PR!

2024-03-21 20:49 UTC, MauAraujo commented on internal/billing/stripe..go
> +}
Responded in the comment above, basically I think that was out of scope for this PR but I still wanted to use those abstractions (but I had to create the no-op methods so the code compiles). Let me know if you rather I delete it in this PR

2024-03-21 20:49 UTC, MauAraujo commented on api/server/shared/config/loader/loader.go
> +	if sc.StripeSecretKey == "" {
Got it, I made this env optional in my latest commit

2024-03-21 20:51 UTC, MauAraujo commented on internal/billing/stripe..go
> +func (s *StripeBillingManager) CreateCustomer(userEmail string, proj *models.Project) (customerID string, err error) {
Got it, I was following the implementation for the old `BillingManager` but I fixed it.

2024-03-21 20:59 UTC, MauAraujo commented on api/types/billing.go
> +type PaymentMethod = *stripe.PaymentMethod
Got it, I created a type with only the necessary stuff in the last commit

2024-03-21 21:34 UTC, stefanmcshane commented on internal/billing/stripe..go
> +}
The billing interface that was there before, does not need to be adhered to and has been defunct for 18+ months. There is a lot of unnecessary code in this repo, so reducing the amount of code where possible will make it much easier to maintain.

2024-03-22 15:16 UTC, MauAraujo commented on internal/billing/stripe..go
> +}
Got it, I was trying to keep the PR smaller but in the end I ended up having to modify the old code. I deleted it in my latest commit. For reference there is still a lot of old code related to billing that I plan to delete in the future.

2024-03-22 20:36 UTC, closed without merging