Create deploying-django-application-non-docker.md
porter-dev/porter pull request #680
Opened 2021-05-15 14:28 UTC by jimcru21

## Pull request type

Django Application Deployment Guide

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Other (please describe): Docs

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

2021-05-17 13:42 UTC, abelanger5 requested changes
Thanks for the PR @jimcru21!! This looks great, just added a few minor fixes that you should resolve, and then I'll add this to our docs. I'll create a new folder called "Application-Specific Guides".

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +> - Docker Registry Integrate on your account ( Work only on ACR, GCR, DOCR )
```suggestion
> - Docker Registry integration on your account ([See docs](https://docs.getporter.dev/docs/linking-an-existing-docker-container-registry))
```

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +1. Install django-allow-cidr ( A Django Middleware to enable use of CIDR IP ranges in ALLOWED_HOSTS )
```suggestion
1. Install `django-allow-cidr` (Django middleware to enable the use of CIDR IP ranges in `ALLOWED_HOSTS`)
```

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +  ALLOWED_CIDR_NETS = os.environ.get("ALLOWED_CIDR_NETS", default='10.0.0.0/8').split(" ")
```suggestion
  ALLOWED_CIDR_NETS = os.environ.get("ALLOWED_CIDR_NETS", default='10.0.0.0/16').split(" ")
```

The k8s CIDR is usually `10.0.0.0/16`, so this might be a better default?

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +4. Add django-allow-cidr middleware on the top of django middleware
```suggestion
4. Add `django-allow-cidr` middleware on the top of Django middleware:
```

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +6. Add static folder then put your html and css files. Locate static url settings and add static file dirs below
```suggestion
6. Add static folder and add your HTML and CSS files. Locate static URL settings and add static file dirs below:
```

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +7. Add Procfile file and add this
```suggestion
7. Add Procfile and add this:
```

2021-05-17 13:42 UTC, abelanger5 commented on docs/deploy/applications/deploying-django-application-non-docker.md
> +  web: gunicorn <project-name>.wsgi -b 0.0.0.0:8989 --timeout 120 (ex. web: gunicorn djangosample.wsgi -b 0.0.0.0:8989 --timeout 120 )
```suggestion
web: gunicorn <project-name>.wsgi -b 0.0.0.0:8989 --timeout 120 
  
For example: 
  
web: gunicorn djangosample.wsgi -b 0.0.0.0:8989 --timeout 120
```

2021-05-18 03:06 UTC, jimcru21 commented
Thanks for the correction and for the help

2021-05-18 12:10 UTC, abelanger5 approved these changes

2021-05-18 12:10 UTC, merged

2021-05-18 12:15 UTC, abelanger5 commented
Merged! Here it is in our docs page: https://docs.getporter.dev/docs/django.