[0.5.0] [Frontend, API] Launchflow Improvements
porter-dev/porter pull request #776
Opened 2021-06-14 15:25 UTC by igalakhov

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

## What is the new behavior?

## Technical Spec/Implementation Notes

2021-06-15 15:04 UTC, jnfrati commented on dashboard/src/components/Button.tsx
> +const Button = ({ children, disabled, onClick }: Props) => {
Hey! Just for a bit of quick advice on typing React components. There's no need to manually type the children prop, as React.FC can do it for you with best practices and support for any future change on that prop 👍 

```suggestion
const Button: React.FC<Props> = ({ children, disabled, onClick }) => {
```

On the other hand if you need to type a component that will not use the children prop you can use React.FunctionComponent that will prevent from accidentally passing children to that component

2021-06-15 15:34 UTC, igalakhov commented on dashboard/src/components/Button.tsx
> +const Button = ({ children, disabled, onClick }: Props) => {
Thanks! Didn't know that this was a thing, will refactor it.

2021-06-15 16:56 UTC, igalakhov commented
Here's a video of a prototype for the initial flow. Does anyone have any thoughts?

https://user-images.githubusercontent.com/25856165/122093414-0fb43e00-cdd9-11eb-8fec-6f85ac56c845.mov

2021-06-15 18:20 UTC, sunguroku commented
> Here's a video of a prototype for the initial flow. Does anyone have any thoughts?
> 
>  github_search_demo_0.mov

Looks great!

2021-06-15 18:34 UTC, abelanger5 requested changes
Added a few minor comments based on what I can see. 

Can we benchmark by setting the number of repos per page to something trivial, like 2? I'd like to make sure this is a significant improvement when `numPages` is 10 or greater.

2021-06-15 18:34 UTC, abelanger5 commented on server/api/git_repo_handler.go
> +	worker := func(cp int, wg *sync.WaitGroup) {
You shouldn't have to pass the `*sync.WaitGroup` to each `go func`. The functions should be able to access the waitgroup, and waitgroup is thread-safe.

2021-06-15 18:34 UTC, abelanger5 commented on server/api/git_repo_handler.go
> +	for i := 1; i <= WCOUNT; i++ {
```suggestion
	for i := 1; i <= max(WCOUNT, numPages); i++ {
```

Pseudo-code, but we probably shouldn't call the `worker` more than we need to?

2021-06-15 19:07 UTC, igalakhov commented on server/api/git_repo_handler.go
> +	worker := func(cp int, wg *sync.WaitGroup) {
Didn't know that. Fixed

2021-06-15 19:08 UTC, igalakhov commented on server/api/git_repo_handler.go
> +	for i := 1; i <= WCOUNT; i++ {
Fixed

2021-06-16 14:32 UTC, igalakhov commented
How should we signal to the user that a buildpack is detected automatically? I have something like below right now, but there are definitely ways to improve to make it more clear:

![image](https://user-images.githubusercontent.com/25856165/122238370-12249f80-ce8e-11eb-8dc3-eb61abf49f3f.png)

2021-06-16 20:36 UTC, igalakhov commented
Does anyone have thoughts about adding better logic for `show_if` in forms? For this PR, the idea is to be able to list variables like `show_if: a b c` and have them be interpreted as an and clause but if anyone has other suggestions that'd be useful too

2021-06-16 20:45 UTC, sunguroku commented
> Does anyone have thoughts about adding better logic for `show_if` in forms? For this PR, the idea is to be able to list variables like `show_if: a b c` and have them be interpreted as an and clause but if anyone has other suggestions that'd be useful too

not immediately salient, but supporting "or" as well as "and" would def be useful in the future too. A potential use case, for example, is a setting that's available only on a select few cloud providers.

2021-06-16 20:52 UTC, abelanger5 commented
> Does anyone have thoughts about adding better logic for `show_if` in forms? For this PR, the idea is to be able to list variables like `show_if: a b c` and have them be interpreted as an and clause but if anyone has other suggestions that'd be useful too

This sounds good, curious about the use-case you're specifically targeting for this PR? 

And any reason why we don't want to explicitly support `and` and `or` operators? Obviously we should avoid building a query language (for now) but I could see cases where the `or` operator would be useful. 

If we decide to support multiple operators, a quick note on syntax moving forward: while most Helm chart developers will likely be writing `form.yaml`, it might be natural to adopt Helm templating syntax. But since the Helm templating syntax (which in this case would be `and (and a b) c` has gotten a fair amount of backlash, it'd seem better to adopt something a bit easier like `jq` operator syntax which would be the more natural `and` and `or` operators, i.e. `a and b and c` (and we're using `jq` elsewhere so this might make sense).

2021-06-17 13:12 UTC, igalakhov commented
The use case I had in mind is that, since we're introducing variables that allow the user to check if a certain type of cloud is being used, they might want to do more complicated statements for showing certain section. As a basic example, they might want to check if they're using some cloud AND that a variable that toggles some database on that cloud is true.

I agree that explicitly supporting `and` and `or` (and maybe like `not`) is a good idea but my main concern about it is backward compatibility (if we ever end up changing the way this is done, the old `form.yaml`s might break). Would we allow for nested statements (for example something like `a and (not b) and (c or d)`)? I think it'd be nice to come up with a short spec for this before I get to implementing any of it to avoid confusion later on.

2021-06-17 21:20 UTC, sunguroku commented
One bug I found: It seems that organizational repositories are not visible with the new search feature and in the list of initially loaded repos. For instance, this repository (`porter-dev/porter`) doesn't show up in the list of repos. Only the personal repositories (`sunguroku/repo_name`) that you own or are invited to are visible.

On current prod: 
![image](https://user-images.githubusercontent.com/65516095/122473701-3668a500-cf90-11eb-8764-c1f1dc21b7a8.png)

On this branch:
![image](https://user-images.githubusercontent.com/65516095/122473781-4f715600-cf90-11eb-89e3-2bb01057dd01.png)

2021-06-18 13:47 UTC, igalakhov commented
@sunguroku it seems like this isn't caused by anything in the backend/frontend logic but rather by the way that github organizational access works. Here's this branch vs prod for me:
<img src="https://user-images.githubusercontent.com/25856165/122570248-90617d00-d019-11eb-9d25-2a49673b311d.png" width=300/> <img src="https://user-images.githubusercontent.com/25856165/122570295-9c4d3f00-d019-11eb-8279-21550796732a.png" width=300/>

2021-06-18 17:30 UTC, abelanger5 requested changes
Working great @igalakhov! A few things:
- Capture an "Enter" keystroke on the search bar to trigger a search
- Benchmark the concurrency solution for listing repos to ensure it's an actual improvement. Just set the number of results per page to something like 2 and look at the network latency between the two solutions. There are cases where concurrency isn't necessarily an improvement and I'd like to make sure this scales to ~1000 repos, which would be 10 API requests total.

2021-06-18 17:58 UTC, igalakhov commented
Doing a test with my own github, about ~130 repos and 2 repos per page:
With concurrency: average around 6 seconds
No concurrency: average around 11 seconds

2021-06-21 13:07 UTC, abelanger5 approved these changes

2021-06-21 21:31 UTC, jusrhee commented
Restyled + made it just autosearch as the user changes the input (since we aren't searching on the backend anyways).

2021-06-21 22:03 UTC, jusrhee commented
> Restyled + made it just autosearch as the user changes the input (since we aren't searching on the backend anyways).
@igalakhov we'll just keep this as a search button for now. Curious to get your thoughts on autosearching though as they update the input

2021-06-21 22:44 UTC, abelanger5 approved these changes

2021-06-21 22:44 UTC, merged