[0.5.0] [Frontend, Forms] Improvements for show_if and other form variables
porter-dev/porter pull request #799
Opened 2021-06-21 13:56 UTC by igalakhov

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [x] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

The `show_if` logic provided by forms only supports one variable, which makes it impossible to do more complicated statements (for instance, needing two variables to be true in order to show something).
Some forms have cloud-specific options with no way to remove them.

## What is the new behavior?

Users can now specify logic with more complex conditionals through yaml:
```yaml
show_if:
  and:
    - a
    - not: b
    - or:
      - c
      - d
```
Every form now has variables like `currentCluster.service.is_aws`, etc. that allow for checking for specific clusters.

## Technical Spec/Implementation Notes
Nothing special, the error handling for form boolean expressions isn't very strong right now, but it shouldn't break anything present right now. Also, if a variable isn't necessarily a boolean, it is converted to a boolean using normal javascript conventions.

2021-06-21 18:18 UTC, igalakhov commented
What would be a good way to add external variables (like the cloud provider for instance) to forms? One way I was thinking is to add it to`FormWrapper` so every form implicitly has access to these variables. But then, I'm not sure if there are any forms that specifically don't want access to these? Does anyone have thoughts on this?

2021-06-22 14:02 UTC, abelanger5 requested changes
Works really well with the basic functionality. Two changes:
- In `/internal/models/templates.go`, change the type of `ShowIf` (line 39) to `interface{}`, since forms aren't parsing at the moment when they're rendered from the backend.
- When the current cluster is changed, the form should re-render. Like if I toggle between an AWS cluster and GKE cluster, the `show_if` logic should be re-evaluated.

2021-06-22 15:37 UTC, igalakhov commented on dashboard/src/components/values-form/ValuesForm.tsx
> +  evalShowIf: (vals: ShowIf) => boolean = (vals: ShowIf) => {
Ah, didn't know about that. Thanks!

2021-06-22 19:31 UTC, abelanger5 approved these changes

2021-06-22 19:31 UTC, merged