[0.6.0] Refactor settings/invite user screen
porter-dev/porter pull request #843
Opened 2021-06-30 22:31 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## Motivation

Based on the huge amount of changes that represents the addition of RBAC on frontend and backend, the idea is to relief the UI changes from that PR and make the visual changes as small as possible, this refactor will allow integrating the RBAC implementation (GH-842) seamlessly without having to change too much the interface. 

## Technical Spec/Implementation Notes

Low fidelity wireframe
![image](https://user-images.githubusercontent.com/23369263/124039471-6032ba80-d9d9-11eb-842f-055fc8d5bf85.png)

2021-07-02 15:15 UTC, jusrhee commented
Looks good. Eventually we'll also add a column for the role, and I think we should just do it as an edit button like stripe:
![image](https://user-images.githubusercontent.com/22849518/124295355-bd885200-db26-11eb-8c6e-325893c39553.png)

That way when you either edit the user or invite a new member, it pulls up the same modal for setting the role:
![image](https://user-images.githubusercontent.com/22849518/124295434-d5f86c80-db26-11eb-881c-3c3a6cacbfd8.png)

2021-07-05 14:29 UTC, abelanger5 requested changes
Looks good @jnfrati! Can the text on the button be changed from black to white? I think it's more readable.

2021-07-06 21:10 UTC, jnfrati commented
@abelanger5 Already fix the status color to correspond with the job status colors!

2021-07-06 23:29 UTC, abelanger5 approved these changes

2021-07-06 23:29 UTC, merged