[0.6.0] Github Org Access Part 2
porter-dev/porter pull request #895
Opened 2021-07-15 19:14 UTC by igalakhov

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Repo search and access old OAuth integration.

## What is the new behavior?

Repo search and access now uses the new GitHub app which should be able to act standalone for all operations we want it to do.

2021-07-21 18:46 UTC, jusrhee approved these changes
Tested on dev - looks good

2021-07-22 15:00 UTC, abelanger5 requested changes
Looks pretty good @igalakhov! Added some minor comments. Will give it one more run-through when the access token/refresh token issue that we discussed are resolved.

2021-07-22 18:02 UTC, igalakhov commented on server/api/oauth_github_handler.go
> -	if r.URL.Query().Get("state") != session.Values["state"] {
To handle installs that happen from other websites (for instance, us linking the app to someone or someone wanting to install it from GitHub directly).

2021-07-22 18:04 UTC, igalakhov commented on server/api/release_handler.go
> +					GithubInstallationID: gitAction.GitRepoID,
Yeah, I wasn't really sure what to do but GitRepoID now refers to Installation IDs instead of Repo IDs

2021-07-22 18:06 UTC, igalakhov commented on server/router/router.go
> +			r.Method( // this endpoint isn't going to be used anymore, should it get deleted?
Done. Frontend repo list is still technically there but isn't accessible to frontend user

2021-07-22 18:10 UTC, igalakhov commented on server/router/router.go
> +			r.Method( // this endpoint isn't going to be used anymore, should it get deleted?
Actually, removed from frontend too

2021-07-22 19:05 UTC, abelanger5 requested changes

2021-07-22 19:05 UTC, abelanger5 commented on server/api/integration_handler.go
> +	_, _, err = oauth.GetAccessToken(oauthInt.AccessToken, oauthInt.RefreshToken, &oauth2.Config{
You may want to change the embedded `oauth2.Config` to a pointer and then pass `app.GithubAppConf.Config` as the `oauth2.Config` param, so you're not instantiating this each time.

2021-07-22 19:05 UTC, abelanger5 commented on server/middleware/auth.go
> +		// TODO: needs to use new github integration implementation
Remove TODO statement?

2021-07-22 19:05 UTC, abelanger5 commented on server/middleware/auth.go
> +		client := github.NewClient(auth.GithubProjectConf.Client(oauth2.NoContext, &oauth2.Token{
Should this be using `auth.GithubProjectConf` since this method is verifying that the user has access to the Github installation id?

2021-07-22 19:05 UTC, abelanger5 commented on server/api/release_handler.go
> +					GithubInstallationID: gitAction.GitRepoID,
Perhaps you can rename `GitRepoID` -> `GithubInstallationID`?

2021-07-22 19:10 UTC, abelanger5 requested changes

2021-07-22 19:10 UTC, abelanger5 commented on internal/integrations/ci/actions/actions.go
> +		tok := &oauth2.Token{
I might be missing something, but shouldn't this also be using `GetAccessToken`?

2021-07-22 19:10 UTC, abelanger5 commented on internal/oauth/config.go
> +func MakeUpdateOAuthIntegrationTokenFunction(o *integrations.OAuthIntegration, repo repository.Repository) func(accessToken []byte, refreshToken []byte, expiry time.Time) error {
Would be good to split this over multiple lines.

2021-07-22 19:10 UTC, abelanger5 commented on internal/oauth/config.go
>  		TokenType:    "Bearer",
I think you need to add the expiry here. Docs for `TokenSource` mention that if the expiry is the zero-value, refresh token isn't used at all.

2021-07-22 19:18 UTC, igalakhov commented on server/api/integration_handler.go
> +	_, _, err = oauth.GetAccessToken(oauthInt.AccessToken, oauthInt.RefreshToken, &oauth2.Config{
Ah, didn't know that was a thing

2021-07-22 19:24 UTC, igalakhov commented on server/middleware/auth.go
> +		client := github.NewClient(auth.GithubProjectConf.Client(oauth2.NoContext, &oauth2.Token{
Yeah, it should (no error happened bc both use the same endpoint to auth)

2021-07-22 23:16 UTC, abelanger5 approved these changes

2021-07-22 23:16 UTC, merged