[0.6.0] Refactor segment implementation
porter-dev/porter pull request #899
Opened 2021-07-19 18:28 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Other (please describe): Refactor

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

It was difficult to track the different ways that we were implementing segment as it was all over the API instead of having a centralized way of doing it

## What is the new behavior?

Created a new analytics package that exports a function to initialize a segment client with helper functions to make tracking more simpler and centralized

2021-07-19 20:28 UTC, abelanger5 requested changes

2021-07-19 20:28 UTC, abelanger5 commented on internal/analytics/segment.go
> +func Initialize(segmentClientKey string) AnalyticsSegmentClient {
Should have comments and called `NewAnalyticsSegment`

2021-07-19 20:28 UTC, abelanger5 commented on internal/analytics/segment.go
> +		fmt.Println("Analytics not enabled")
You should pass in a Logger interface and use that instead of `fmt...`

2021-07-19 20:28 UTC, abelanger5 commented on internal/analytics/segment.go
> +package analytics
You should declare the precise analytics that are being tracked in this package, perhaps in a file called `analytics.go`? For example, instead of `segment.NewProperties().Set("email", user.Email)`, have an analytics type called `User` which has a method that returns `id` and a method that returns a `segment.Property` (or whatever the struct is called).

2021-07-20 20:34 UTC, abelanger5 requested changes
Looks great @jnfrati, that's exactly what I had in mind. 

I added some minor comments, but this definitely cleans up the handlers.

2021-07-20 20:34 UTC, abelanger5 commented on internal/analytics/identifiers.go
> +type SegmentIdentifier interface {
Comment all exported interfaces, structs, and methods.

2021-07-20 20:34 UTC, abelanger5 commented on internal/analytics/segment.go
> +	Initialize the segment client and return a superset of it, the AnalyticsSegmentClient will handle cases when
```suggestion
// Initialize the segment client and return a superset of it, the AnalyticsSegmentClient will handle cases when
// the segment client failed on initialization or not enabled
```

Can you modify these comments to keep the style consistent with the other parts of the code?

2021-07-20 20:34 UTC, abelanger5 commented on internal/analytics/tracks.go
> +func CreateSegmentRedeployViaWebhookTrack(userId string, repository interface{}) *SegmentRedeployViaWebhookTrack {
Can you document what the `repository` argument is? Also, i'm not sure why this needs to be an `interface{}`. AFAIK the repository argument is the image repository URI, which is always a string.

2021-07-20 20:34 UTC, abelanger5 commented on internal/analytics/README.md
> +# How the analytics package works
Perhaps we want to make this a `doc.go` file? This will automatically render on the `pkg.go.dev` site. This is suggested by: https://blog.golang.org/godoc, and it links to the example: https://golang.org/src/encoding/gob/doc.go. 

If we want to keep this as a markdown file, I think it should be moved to `/docs/developing` since I'm not sure we want to keep markdown files in the source folders. These might get accidentally mounted in a Docker container or added as part of the build.

2021-07-20 20:40 UTC, jnfrati commented on internal/analytics/tracks.go
> +func CreateSegmentRedeployViaWebhookTrack(userId string, repository interface{}) *SegmentRedeployViaWebhookTrack {
Didn't exactly knew what was coming there, so I ended up setting the same type as [the repository on the usage file](https://github.com/porter-dev/porter/blob/master/server/api/release_handler.go#L1096), just to make sure I ended up using the `interface{}` but if you say it should be a string I can update that really quick 👍

2021-07-20 20:42 UTC, jnfrati commented on internal/analytics/identifiers.go
> +type SegmentIdentifier interface {
As the only things used outside the package are the struct constructors and the functions on segment.go, I wasn't sure if I should leave this exported. What do you think? Either way I'll add proper comments to the constructor so we can know what those metrics are used for.

2021-07-20 20:52 UTC, abelanger5 commented on internal/analytics/identifiers.go
> +type SegmentIdentifier interface {
Should other packages call any of the methods in the `SegmentIdentifier` interface? If not, this can be unexported.

2021-07-20 20:53 UTC, abelanger5 commented on internal/analytics/tracks.go
> +func CreateSegmentRedeployViaWebhookTrack(userId string, repository interface{}) *SegmentRedeployViaWebhookTrack {
Yep, sounds good. I believe it should always be a string.

2021-07-22 19:36 UTC, abelanger5 approved these changes
Awesome work @jnfrati!

2021-07-22 19:36 UTC, merged