[0.7.0] Add auto scaling threshold line to application metrics
porter-dev/porter pull request #929
Opened 2021-07-26 17:40 UTC by jnfrati

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Currently, horizontal pod autoscaling is something difficult to visualize under the metrics tab. There's a lack of history as well as some additional info on when the autoscaling is going to happen

Issue Number: #898 
Closes #787 

## What is the new behavior?

As referenced on the issue, this PR will cover the first graph that will show a threshold that announces the next step before k8s will autoscale the pods as well as new Prometheus metrics that will cover the lack of historical data on dead pods.

## Technical Spec/Implementation Notes

A quick reference on how the graph will look like
![image](https://user-images.githubusercontent.com/23369263/127033518-bae5b082-ef15-4074-b51f-340f0783d291.png)

The new prometheus queries will be handled by regex expressions that depends on the selected controller to get all the pods that have stored data on prometheus.

2021-07-30 12:08 UTC, abelanger5 commented
Before this can be merged, the backend implementations should query for metrics named `kube_horizontal_pod_autoscaler...` since this metric was renamed in a recent version of `kube-state-metrics`. It should default to using this metric if it exists, since this also likely means the `kube-state-metrics` chart was upgraded.

2021-08-02 11:46 UTC, abelanger5 requested changes
Few tiny comments @jnfrati, otherwise this is ready to be merged 👍

2021-08-02 11:46 UTC, abelanger5 commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/metrics/AreaChart.tsx
> +// export default withTooltip<AreaProps, TooltipData>();
Remove commented line

2021-08-02 11:46 UTC, abelanger5 commented on dashboard/src/main/home/cluster-dashboard/expanded-chart/metrics/MetricNormalizer.ts
> +export class MetricNormalizer {
I am unsure what this object does. Could you add a comment?

2021-08-02 12:03 UTC, abelanger5 approved these changes

2021-08-02 12:03 UTC, merged

2021-08-02 16:57 UTC, jusrhee commented
@jnfrati turned on autoscaling for a service that didn't have autoscaling enabled initially and got this:
![image](https://user-images.githubusercontent.com/22849518/127897235-2f37683a-37f4-43b7-b65c-10eb14b242de.png)

Is there a clean way to handle this edge case?